# -*- coding: utf-8 -*-
"""Face Mask Live Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DeUhxEIO6hZl0Qsje5b_OIkEf2dTv2lA
"""

!pip install opencv-python-headless tensorflow scikit-learn

import kagglehub
path = kagglehub.dataset_download("omkargurav/face-mask-dataset")
print("Path to dataset files:", path)

import shutil
shutil.copytree(path, "data")

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.models import load_model
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode
from google.colab import files
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Dropout

IMG_SIZE = 64
data = []
labels = []

categories = ["with_mask", "without_mask"]
data_path = "/content/data/data"
for label, category in enumerate(categories):
    path = os.path.join(data_path, category)

    for img_name in os.listdir(path):
        img_path = os.path.join(path, img_name)

        image = cv2.imread(img_path)
        if image is None:
            continue

        image = cv2.resize(image, (IMG_SIZE, IMG_SIZE))
        data.append(image)
        labels.append(label)

data = np.array(data, dtype="float32") / 255.0
labels = to_categorical(labels, 2)

X_train, X_test, y_train, y_test = train_test_split(
    data, labels, test_size=0.2, random_state=42, shuffle=True
)

model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(64,64,3)),
    MaxPooling2D(2,2),

    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Conv2D(128, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(2, activation='softmax')
])
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
)
datagen = ImageDataGenerator(
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
)
history = model.fit(
    X_train,
    y_train,
    epochs=20,
    validation_data=(X_test, y_test),
    batch_size=32,
    callbacks=[early_stop],
    verbose=1
)
model.save("/content/mask_model.h5")

print("✅ Model trained and saved!")



face_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
)

model = load_model("/content/mask_model.h5")
categories = ["With Mask", "Without Mask"]

uploaded = files.upload()

for file_name in uploaded.keys():
    img = cv2.imread(file_name)
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.1, 5)
    for (x, y, w, h) in faces:
        face = img[y:y+h, x:x+w]
        face_input = cv2.resize(face, (64,64))
        face_input = face_input.astype("float32") / 255.0
        face_input = np.expand_dims(face_input, axis=0)
        prediction = model.predict(face_input)
        label = categories[np.argmax(prediction)]
        color = (0, 255, 0) if label == "With Mask" else (255, 0, 0)
        cv2.rectangle(img_rgb, (x, y), (x+w, y+h), color, 2)
        cv2.putText(
            img_rgb,
            label,
            (x, y - 10),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8,
            color,
            2
        )
        print("Prediction:", label)

plt.figure(figsize=(8,6))
plt.imshow(img_rgb)
plt.axis("off")
plt.title("Face Mask Detection Result")
plt.show()

def take_photo(filename='photo.jpg', quality=0.8):
    js = Javascript('''
        async function takePhoto(quality) {
            const div = document.createElement('div');
            const video = document.createElement('video');
            const button = document.createElement('button');

            button.textContent = 'Capture';
            div.appendChild(video);
            div.appendChild(button);
            document.body.appendChild(div);

            const stream = await navigator.mediaDevices.getUserMedia({video: true});
            video.srcObject = stream;
            await video.play();

            google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);

            await new Promise((resolve) => button.onclick = resolve);

            const canvas = document.createElement('canvas');
            canvas.width = video.videoWidth;
            canvas.height = video.videoHeight;
            canvas.getContext('2d').drawImage(video, 0, 0);

            stream.getTracks().forEach(track => track.stop());
            div.remove();

            return canvas.toDataURL('image/jpeg', quality);
        }
    ''')
    display(js)

    data = eval_js('takePhoto({})'.format(quality))
    binary = b64decode(data.split(',')[1])

    with open(filename, 'wb') as f:
        f.write(binary)

    return filename

model = load_model("/content/mask_model.h5")
categories = ["With Mask", "Without Mask"]
print("📸 Press ENTER to capture, type 'q' to stop")
while True:
    key = input("➡ Press ENTER to capture or q to quit: ")
    if key.lower() == 'q':
        print("🛑 Stopped by user")
        break
    filename = take_photo()
    img = cv2.imread(filename)
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    plt.imshow(img_rgb)
    plt.axis("off")
    plt.title("📸 Captured Image")
    plt.show()
    img_resized = cv2.resize(img, (64, 64))
    img_array = np.expand_dims(img_resized, axis=0) / 255.0
    prediction = model.predict(img_array)
    label = categories[np.argmax(prediction)]
    print("🧠 Prediction:", label)
    if label == "Without Mask":
        print("⚠️ Mask NOT detected!")
    else:
        print("✅ Mask detected!")

